name: .NET Core Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      # packaging and uploading the nupkg, it should be enough to build this on one OS, it can be used for all OSes
      - name: Package
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dotnet pack src/Dynatrace.OpenTelemetry.Exporter.Metrics --configuration Release --no-build

      - name: Archive nupkg
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: '**/bin/**/*.*nupkg'
